### ISSUE TITLE
working with Service account

### ISSUE THREAD

**Issue by zishanj** [elsesiy/GAppAuth#1]
Any idea how to use Service account JSON file for authentication and then use Google Calendar API to read calendar?

**Comment by elsesiy** [comment]
Yes, that's exactly what this wrapper is for. Just follow the instructions to set up your project with the service account file and define the scope you need for the Google Calendar API...

Let me know if you need further assistance.

**Comment by zishanj** [comment]
I have tried but this seems to be a 3-legged authentication. I am looking for 2-legged authentication with Google services account.

**Comment by elsesiy** [comment]
@zishanj Since Google split the form inputs for user and password to two different pages, there's no way you can implement a 2-legged authentication anymore as far as I know.

**Comment by elsesiy** [comment]
Closed due to inactivity.
