### ISSUE TITLE
Redirection issue

### ISSUE THREAD

**Issue by awaismubeen** [elsesiy/GAppAuth#12]
when I try to login as 
`GAppAuth.shared.retrieveExistingAuthorizationState()
       if GAppAuth.shared.isAuthorized() {
           let authorization = GAppAuth.shared.getCurrentAuthorization()
           //self.updateUI(authorization)
       }else{
        do{
            try GAppAuth.shared.authorize(callback: { auth in
                print(auth)
            })
        }catch{
            print("error")
        }
    }`
it leads to login page but after selecting the account it showd
<img width="737" alt="Screen Shot 2020-01-15 at 6 26 33 PM" src="https://user-images.githubusercontent.com/7234452/72438503-c36d6480-37c6-11ea-90e9-b4959c6b4648.png">
what could be gone wrong?

**Comment by elsesiy** [comment]
@AwaisMobeen It looks like you didn't properly register the URL-scheme which is necessary for Safari to handle the redirect. Did you try the example project I provided? See [here](https://github.com/elsesiy/GAppAuth#macos) for the setup instructions and make sure you don't miss anything.
