### ISSUE TITLE
Subscribe to token change events?

### ISSUE THREAD

**Issue by gazzer82** [elsesiy/GAppAuth#14]
I am using this in an iOS app, and need to be updated when the token is refreshed.

I see there are the GAppAuth.shared.stateChangeCallback and GAppAuth.shared.errorCallback, but I can't quit work out how to use them.

Does anyone have any pointers?

Thanks

Gareth

**Comment by elsesiy** [comment]
@gazzer82 These are standard swift callbacks e.g.
```
GAppAuth.shared.stateChangeCallback = { state -> Void in
    
}

GAppAuth.shared.errorCallback = { state, err -> Void in
    
}
```

Please let me know if this doesn't answer the question, thanks!
