### ISSUE TITLE
Feature request: SPM support

### ISSUE THREAD

**Issue by ptsochantaris** [elsesiy/GAppAuth#16]
Thank you so much for making this brilliant project, it helped un-stick quite a few projects on macOS which were pinned down because of Google's inability to update their SDKs, and it works brilliantly.

I was wondering if you have considered adding Swift Package Manager support so we can take the "liberation" of the projects one step further and leave Cocoapods behind too ;)

**Comment by elsesiy** [comment]
@ptsochantaris Thank you! I just noticed that Google added SPM support too so this should be possible now. Do you want to submit a PR?

**Comment by ptsochantaris** [comment]
Hi @elsesiy, sorry for the slow reply - sure, would be happy to. Will need to do some digging around first, but will do! :)

**Comment by ptsochantaris** [comment]
Thanks for merging the PR!

For a simple optional improvement, the version tag on `master` can to be bumped - e.g. to 1.6.1. No need to publish a release or anything.

Otherwise by default SwiftPM will try to check out the latest tag (1.6.0) which doesn't present the Package.swift file. If a tag is added, then it will check that one out instead and find the Package.swift file.

This obviously is not a blocker, since you can select "master" from the options in Xcode when adding the package and all is well, but then you don't get the fancy version tracking ;) but I thought I'd mention it.

Once again, thank you for this great project, it's so nice not having to depend on Google (whose SDK is still broken) for basic functionality like this.
