### ISSUE TITLE
Support for Mac OSX?

### ISSUE THREAD

**Issue by grantkemp** [elsesiy/GAppAuth#3]
Hi - great work - do you know if you plan to make it compatible with Mac OSX?
```[!] The platform of the target `Performance Tool` (macOS 10.13) is not compatible with `GAppAuth (1.1.0)`, which does not support `osx`.```

**Comment by elsesiy** [comment]
Hi, thanks! I haven't really thought about it as I'm only using it for iOS so far. Shouldn't be too much work to make it work for osx as well. Let me check and get back to you in a couple of days, cheers!

**Comment by elsesiy** [comment]
@grantkemp Quick update: I'm almost ready with OS X support but am currently stuck with a keychain issue. I'll try to finish by the end of next week.

**Comment by grantkemp** [comment]
awesome! I have actually made my own approach which is working - but if you are working on it then will port my solution over to yours.

**Comment by elsesiy** [comment]
@grantkemp @martindufort Would you mind testing [this branch](https://github.com/elsesiy/GAppAuth/tree/feat/issue-3-osx-support)?
